/*AQUI EU ESTOU MANDANDO OS COMANDOS PARA CRIAR E USAR O BANCO DE DADOS*/

CREATE DATABASE bd_chamados;
USE bd_chamados ;
 
/*AQUI EU DOU INICO A CRIAÇÃO DA PRIMEIRA TABELA DO BANCO DE DADOS*/

CREATE TABLE Usuarios (
Nome VARCHAR (50),
Email VARCHAR (80),
Cpf INT (20),
Setor VARCHAR (50)
);

/*OS DADOS INFORMADOS AQUI ABAIXO ANTES DA CRIAÇÃO DA PRÓXIMA TABELA SÃO JUSTAMENTE PARA 
ARRUMAR OS DADOS QUE FALTARAM AO DECLARAR OS CAMPOS NA TABELA*/

ALTER TABLE Usuarios ADD COLUMN Id_Usuario INT UNSIGNED AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE Usuarios MODIFY Email VARCHAR(100) NOT NULL;
ALTER TABLE Usuarios ADD CONSTRAINT Email UNIQUE (Email);

ALTER TABLE Usuarios MODIFY Nome VARCHAR(50) NOT NULL;
ALTER TABLE Usuarios ADD CONSTRAINT Nome UNIQUE (Nome);

ALTER TABLE Usuarios MODIFY Cpf INT(20) NOT NULL;
ALTER TABLE Usuarios ADD CONSTRAINT Cpf UNIQUE (Cpf);

ALTER TABLE Usuario Modify Setor VARCHAR(50) NOT NULL;
ALTER TABLE Usuarios ADD CONSTRAINT Setor UNIQUE (Setor);

CREATE TABLE CHAMADO (
Id_Chamado INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
Id_Usuario INT UNSIGNED,
Descricao VARCHAR(200) NOT NULL UNIQUE,
dataChamado DATE NOT NULL UNIQUE,
Setor VARCHAR (80) UNIQUE,
/* ADICIONAR A COMUNICAÇÃO DE FERIGN KEY E TERMINAR DE ACRESCENTAR DADOS*/


);
